DROP TABLE IF EXISTS inout;
DROP TABLE IF EXISTS lagersaldo;
DROP TABLE IF EXISTS products;

CREATE TABLE inout (
    product VARCHAR(200) NOT NULL,
    cityTo VARCHAR(200) NOT NULL,
    cityFrom VARCHAR(200) NOT NULL,
    amount INT NOT NULL,
    datePosted TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lagersaldo (
    cityID VARCHAR(200) NOT NULL,
    product VARCHAR(200) NOT NULL,
    city VARCHAR(200) NOT NULL,
    amount INT NOT NULL
);

CREATE TABLE products (
    ID VARCHAR(200) NOT NULL,
    product VARCHAR(200) NOT NULL,
    price INT NOT NULL
);
